version: '3'
services:
  rag-chatbot:
    build: .
    ports:
      - "7860:7860"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - HOST=0.0.0.0
      - PORT=7860
      - ENABLE_VECTOR_DB_PERSISTENCE=True
      - VECTOR_DB_PATH=/app/data/chroma_db
      - MAX_MEMORY_TOKENS=3000
      - LOG_LEVEL=INFO
    restart: unless-stopped
    depends_on:
      - vector-db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:7860/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  vector-db:
    image: vector-db-image
    volumes:
      - ./vector-db-data:/data
    restart: unless-stopped